# Generated by Django 3.1.2 on 2020-10-08 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drinks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=1000)),
                ('percentage', models.CharField(max_length=100)),
                ('times_hourly', models.IntegerField(blank=True, null=True)),
                ('times_daily', models.IntegerField(blank=True, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('severity', models.PositiveIntegerField()),
            ],
            options={
                'ordering': ['severity'],
            },
        ),
    ]
