# Generated by Django 3.1.2 on 2020-10-10 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20201008_1710'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeverityLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('severity', models.PositiveIntegerField()),
                ('bac', models.FloatField()),
                ('bio', models.TextField(max_length=10000)),
                ('name', models.CharField(max_length=1000)),
            ],
        ),
    ]
