# Generated by Django 3.1.2 on 2020-10-10 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_severitylevel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='severitylevel',
            options={'ordering': ['severity']},
        ),
        migrations.RemoveField(
            model_name='drink',
            name='times_daily',
        ),
        migrations.RemoveField(
            model_name='drink',
            name='times_hourly',
        ),
    ]
