# Generated by Django 3.1.2 on 2020-10-10 09:10

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20201010_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='severitylevel',
            name='bio',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
