# Generated by Django 3.1.2 on 2020-10-17 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20201010_1210'),
    ]

    operations = [
        migrations.AddField(
            model_name='drink',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
